---
collections:
  - name: amazon.aws
  - name: ansible.controller
  - name: community.crypto
  - name: community.general
  - name: ansible.posix
  - name: datadog.dd
  - name: infra.eda_configuration
  - name: dynatrace.oneagent
  - name: servicenow.itsm