---
- name: Respond to Datadog Nginx alerts
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        endpoint: /datadog-webhook
      filters:
        - ansible.eda.insert_hosts_to_meta:
            host_path: payload.hostname

  rules:
    - name: Remediate Nginx service
      condition: >
        event.payload.alert_transition == "Triggered" and
        event.payload.alert_title is search("Nginx Not Running") and
        event.payload.alert_query is search("nginx.can_connect") and
        event.payload.alert_type == "error"
      action:
        run_job_template:
          name: eda-monitoring-demo - DataDog Remediation
          organization: Default
          job_args:
            extra_vars:
              alert_id: "{{ event.payload.alert_id }}"
              alert_title: "{{ event.payload.alert_title }}"
              alert_status: "{{ event.payload.alert_status }}"
              alert_timestamp: "{{ event.payload.date }}"
              target_host: "{{ event.payload.hostname }}"
              alert_last_updated: "{{ event.payload.last_updated }}"
              alert_message: "{{ event.payload.alert_message }}"
              alert_link: "{{ event.payload.link }}"

    - name: Log Nginx recovery
      condition: >
        event.payload.alert_transition == "Recovered" and
        event.payload.alert_title is search("Nginx Not Running") and
        event.payload.alert_query is search("nginx.can_connect") and
        event.payload.alert_type == "success"
      action:
        debug:
          msg: >
            Nginx service recovered on host {{ event.payload.hostname }}
