---
- name: Respond to Datadog Nginx alerts
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        endpoint: /datadog-webhook

  rules:
    - name: Remediate Nginx service
      condition: >
        event.payload.alert_transition == "Triggered" and
        event.payload.alert_title is search("Nginx Not Running") and
        event.payload.alert_query is search("nginx.can_connect") and
        event.payload.alert_type == "error"
      action:
        run_job_template:
          name: remediate_nginx.yml
          organization: Default
          job_args:
            extra_vars:
              target_host: "{{ event.payload.hostname.split }}"
              alert_title: "{{ event.payload.alert_title }}"
              alert_message: "{{ event.payload.alert_message }}"
              alert_timestamp: "{{ event.payload.date }}"

    - name: Log Nginx recovery
      condition: >
        event.payload.alert_transition == "Recovered" and
        event.payload.alert_title is search("Nginx Not Running") and
        event.payload.alert_query is search("nginx.can_connect") and
        event.payload.alert_type == "success"
      action:
        debug:
          msg: >
            Nginx service recovered on host {{ event.payload.hostname.split }}

