name: Build Execution Environment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible-builder

    - name: Log in to Red Hat Registry
      run: |
        podman login -u '${{ secrets.REDHAT_REGISTRY_USER }}' -p '${{ secrets.REDHAT_REGISTRY_PASSWORD }}' registry.redhat.io

    - name: Build Execution Environment
      env:
        CONTENT_HUB_TOKEN: ${{ secrets.CONTENT_HUB_TOKEN }}
      run: |
        ansible-builder build -t eda-monitoring-demo-ee:latest --build-arg CONTENT_HUB_TOKEN=${CONTENT_HUB_TOKEN}

    - name: Log in to Quay.io
      run: |
        podman login -u '${{ secrets.QUAY_USERNAME }}' -p '${{ secrets.QUAY_PASSWORD }}' quay.io

    - name: Push to Quay.io
      run: |
        podman tag eda-monitoring-demo-ee:latest quay.io/${{ secrets.QUAY_NAMESPACE }}/eda-monitoring-demo-ee:latest
        podman push quay.io/${{ secrets.QUAY_NAMESPACE }}/eda-monitoring-demo-ee:latest

    - name: Push to Quay.io with commit SHA tag
      if: github.event_name != 'pull_request'
      run: |
        podman tag eda-monitoring-demo-ee:latest quay.io/${{ secrets.QUAY_NAMESPACE }}/eda-monitoring-demo-ee:${{ github.sha }}
        podman push quay.io/${{ secrets.QUAY_NAMESPACE }}/eda-monitoring-demo-ee:${{ github.sha }}